### ISSUE TITLE
Schema Choice for defining Parameters

### ISSUE THREAD

**Issue by moredhel** [faaslang/faaslang#28]
I'm curious why you chose to implement new type-checking logic. There is some work already in this area http://json-schema.org/. Was this considered?

An interesting project, I am watching how this will progress.

**Comment by thedavidmeister** [comment]
transit also https://github.com/cognitect/transit-format

which has implementations for about a dozen popular langs https://github.com/cognitect/transit-format/wiki/Community-Implementations

**Comment by keithwhor** [comment]
Apologies for taking a while to get to this. :)

We've written our own type-checking logic because we needed a specification that was robust, and one that we could build off of without having to refer to an external committee or community in a worst-case scenario. Our roadmap for FaaSlang hasn't been published because it's still very much under active development and growing organically in response to customer needs (mostly as a result of those shipping APIs to [Standard Library](https://stdlib.com)).

There's a hell of a lot we'd like to do with FaaSlang, optimistically, that includes object schema validation and more. We may look into JSON Schema in the future, for now we have a pretty solidly tested specification and implemented gateway.

**Comment by keithwhor** [comment]
Updates on this: we just merged in version `0.4.0` which adds `schema` support to object types. It's not an exact match to the JSON Schema spec, but I'm sure you'll see some convergent evolution over time. :)

https://github.com/faaslang/faaslang/blob/master/tests/files/comprehensive/schema/schema.js
